/**
 * All Kard mock data lives in this file.
 *
 * Nothing outside of `lib/api-client.ts` should import from here — components
 * receive data through props so the mock layer can be deleted once the real
 * Kard API is wired up.
 */

import type {
  Location,
  Merchant,
  MerchantCustomer,
  MerchantDashboardStats,
  PointTransaction,
  Redemption,
  Reward,
  User,
  Wallet,
} from "@/lib/api-types";

/** Timestamps are relative so "Today" / "Yesterday" labels stay believable. */
function daysAgo(days: number, hour = 9, minute = 15): string {
  const date = new Date();
  date.setDate(date.getDate() - days);
  date.setHours(hour, minute, 0, 0);
  return date.toISOString();
}

/* -------------------------------------------------------------------------- */
/* Session                                                                     */
/* -------------------------------------------------------------------------- */

/** The signed-in customer for every customer facing screen. */
export const MOCK_CURRENT_USER_ID = "usr_demo_vishanth";

/** The signed-in merchant for every /merchant screen. */
export const MOCK_CURRENT_MERCHANT_ID = "mch_medici";

export const mockUsers: User[] = [
  {
    id: MOCK_CURRENT_USER_ID,
    fullName: "Vishanth Hari",
    firstName: "Vishanth",
    email: "vishanth@utexas.edu",
    memberId: "KARD-8241-0973",
    avatarUrl: null,
    joinedAt: daysAgo(214),
    homeCity: "Austin, TX",
  },
];

/* -------------------------------------------------------------------------- */
/* Merchants + locations                                                       */
/* -------------------------------------------------------------------------- */

export const mockMerchants: Merchant[] = [
  {
    id: "mch_medici",
    slug: "medici-roasting",
    name: "Medici Roasting",
    category: "Coffee",
    tagline: "Small-batch coffee roasted on Guadalupe",
    logoText: "MR",
    logoUrl: null,
    brandColor: "#1F3A2E",
    pointsPerDollar: 1,
    locationCount: 3,
  },
  {
    id: "mch_pterrys",
    slug: "p-terrys",
    name: "P. Terry's",
    category: "Burgers",
    tagline: "Fresh burgers, Austin original",
    logoText: "PT",
    logoUrl: null,
    brandColor: "#7F1D1D",
    pointsPerDollar: 1,
    locationCount: 4,
  },
  {
    id: "mch_taco_joint",
    slug: "taco-joint",
    name: "Taco Joint",
    category: "Tacos",
    tagline: "Breakfast tacos all day",
    logoText: "TJ",
    logoUrl: null,
    brandColor: "#9A3412",
    pointsPerDollar: 1,
    locationCount: 2,
  },
  {
    id: "mch_thunderbird",
    slug: "thunderbird-coffee",
    name: "Thunderbird Coffee",
    category: "Coffee",
    tagline: "Neighborhood coffee bar",
    logoText: "TB",
    logoUrl: null,
    brandColor: "#0F766E",
    pointsPerDollar: 1,
    locationCount: 2,
  },
  {
    id: "mch_juan",
    slug: "juan-in-a-million",
    name: "Juan in a Million",
    category: "Breakfast",
    tagline: "East Austin breakfast institution",
    logoText: "JM",
    logoUrl: null,
    brandColor: "#854D0E",
    pointsPerDollar: 1,
    locationCount: 1,
  },
  {
    id: "mch_quacks",
    slug: "quacks-bakery",
    name: "Quack's 43rd St Bakery",
    category: "Bakery",
    tagline: "Cakes, cookies and cold brew",
    logoText: "QB",
    logoUrl: null,
    brandColor: "#5B21B6",
    pointsPerDollar: 1,
    locationCount: 1,
  },
  {
    id: "mch_via313",
    slug: "via-313",
    name: "Via 313 Pizza",
    category: "Pizza",
    tagline: "Detroit-style pan pizza",
    logoText: "V3",
    logoUrl: null,
    brandColor: "#3F3F46",
    pointsPerDollar: 1,
    locationCount: 3,
  },
  {
    id: "mch_juiceland",
    slug: "juiceland",
    name: "JuiceLand",
    category: "Juice",
    tagline: "Smoothies and cold-pressed juice",
    logoText: "JL",
    logoUrl: null,
    brandColor: "#166534",
    pointsPerDollar: 2,
    locationCount: 5,
  },
  {
    id: "mch_thundercloud",
    slug: "thundercloud-subs",
    name: "Thundercloud Subs",
    category: "Sandwiches",
    tagline: "Fast, fresh, Austin-made subs",
    logoText: "TC",
    logoUrl: null,
    brandColor: "#1E3A8A",
    pointsPerDollar: 1,
    locationCount: 4,
  },
];

export const mockLocations: Location[] = [
  {
    id: "loc_medici_guadalupe",
    merchantId: "mch_medici",
    name: "Guadalupe",
    addressLine1: "2222 Guadalupe St",
    city: "Austin",
    region: "TX",
    postalCode: "78705",
    distanceMiles: 0.2,
    hours: "7:00 AM – 8:00 PM",
  },
  {
    id: "loc_medici_west_lynn",
    merchantId: "mch_medici",
    name: "West Lynn",
    addressLine1: "1101 West Lynn St",
    city: "Austin",
    region: "TX",
    postalCode: "78703",
    distanceMiles: 1.4,
    hours: "7:00 AM – 7:00 PM",
  },
  {
    id: "loc_medici_congress",
    merchantId: "mch_medici",
    name: "South Congress",
    addressLine1: "1200 S Congress Ave",
    city: "Austin",
    region: "TX",
    postalCode: "78704",
    distanceMiles: 2.9,
    hours: "7:00 AM – 6:00 PM",
  },
  {
    id: "loc_pterrys_guadalupe",
    merchantId: "mch_pterrys",
    name: "Guadalupe",
    addressLine1: "2915 Guadalupe St",
    city: "Austin",
    region: "TX",
    postalCode: "78705",
    distanceMiles: 0.5,
    hours: "7:00 AM – 12:00 AM",
  },
  {
    id: "loc_pterrys_barton",
    merchantId: "mch_pterrys",
    name: "Barton Springs",
    addressLine1: "1400 S Lamar Blvd",
    city: "Austin",
    region: "TX",
    postalCode: "78704",
    distanceMiles: 2.6,
    hours: "7:00 AM – 12:00 AM",
  },
  {
    id: "loc_taco_joint_duval",
    merchantId: "mch_taco_joint",
    name: "Duval",
    addressLine1: "4600 Duval St",
    city: "Austin",
    region: "TX",
    postalCode: "78751",
    distanceMiles: 1.1,
    hours: "7:00 AM – 3:00 PM",
  },
  {
    id: "loc_taco_joint_riverside",
    merchantId: "mch_taco_joint",
    name: "Riverside",
    addressLine1: "1200 E Riverside Dr",
    city: "Austin",
    region: "TX",
    postalCode: "78741",
    distanceMiles: 3.2,
    hours: "7:00 AM – 3:00 PM",
  },
  {
    id: "loc_thunderbird_manor",
    merchantId: "mch_thunderbird",
    name: "Manor Road",
    addressLine1: "2200 Manor Rd",
    city: "Austin",
    region: "TX",
    postalCode: "78722",
    distanceMiles: 1.8,
    hours: "6:30 AM – 9:00 PM",
  },
  {
    id: "loc_juan_east",
    merchantId: "mch_juan",
    name: "East Sixth",
    addressLine1: "2300 E Cesar Chavez St",
    city: "Austin",
    region: "TX",
    postalCode: "78702",
    distanceMiles: 2.3,
    hours: "7:00 AM – 3:00 PM",
  },
  {
    id: "loc_quacks_43rd",
    merchantId: "mch_quacks",
    name: "43rd Street",
    addressLine1: "411 E 43rd St",
    city: "Austin",
    region: "TX",
    postalCode: "78751",
    distanceMiles: 1.3,
    hours: "7:00 AM – 9:00 PM",
  },
  {
    id: "loc_via313_rainey",
    merchantId: "mch_via313",
    name: "Rainey Street",
    addressLine1: "61 Rainey St",
    city: "Austin",
    region: "TX",
    postalCode: "78701",
    distanceMiles: 2.1,
    hours: "11:00 AM – 11:00 PM",
  },
  {
    id: "loc_juiceland_barton",
    merchantId: "mch_juiceland",
    name: "Barton Springs",
    addressLine1: "1625 Barton Springs Rd",
    city: "Austin",
    region: "TX",
    postalCode: "78704",
    distanceMiles: 2.4,
    hours: "7:00 AM – 9:00 PM",
  },
  {
    id: "loc_thundercloud_dean_keeton",
    merchantId: "mch_thundercloud",
    name: "Dean Keeton",
    addressLine1: "1608 W 6th St",
    city: "Austin",
    region: "TX",
    postalCode: "78703",
    distanceMiles: 1.6,
    hours: "10:00 AM – 9:00 PM",
  },
];

/* -------------------------------------------------------------------------- */
/* Wallets                                                                     */
/* -------------------------------------------------------------------------- */

export const mockWallets: Wallet[] = [
  {
    id: "wal_medici",
    userId: MOCK_CURRENT_USER_ID,
    merchantId: "mch_medici",
    pointsBalance: 82,
    lifetimePoints: 612,
    visitCount: 14,
    lastActivityAt: daysAgo(0, 8, 42),
  },
  {
    id: "wal_pterrys",
    userId: MOCK_CURRENT_USER_ID,
    merchantId: "mch_pterrys",
    pointsBalance: 45,
    lifetimePoints: 268,
    visitCount: 9,
    lastActivityAt: daysAgo(1, 19, 5),
  },
  {
    id: "wal_taco_joint",
    userId: MOCK_CURRENT_USER_ID,
    merchantId: "mch_taco_joint",
    pointsBalance: 120,
    lifetimePoints: 430,
    visitCount: 11,
    lastActivityAt: daysAgo(2, 12, 30),
  },
  {
    id: "wal_thunderbird",
    userId: MOCK_CURRENT_USER_ID,
    merchantId: "mch_thunderbird",
    pointsBalance: 105,
    lifetimePoints: 305,
    visitCount: 7,
    lastActivityAt: daysAgo(5, 10, 10),
  },
  {
    id: "wal_juan",
    userId: MOCK_CURRENT_USER_ID,
    merchantId: "mch_juan",
    pointsBalance: 68,
    lifetimePoints: 168,
    visitCount: 4,
    lastActivityAt: daysAgo(9, 9, 25),
  },
];

/* -------------------------------------------------------------------------- */
/* Rewards                                                                     */
/* -------------------------------------------------------------------------- */

export const mockRewards: Reward[] = [
  {
    id: "rwd_medici_pastry",
    merchantId: "mch_medici",
    name: "Free Pastry",
    description: "Any pastry from the case, baked that morning.",
    pointsRequired: 75,
    isActive: true,
    createdAt: daysAgo(180),
  },
  {
    id: "rwd_medici_drink",
    merchantId: "mch_medici",
    name: "Free Drink",
    description: "Any drink on the menu, any size.",
    pointsRequired: 100,
    isActive: true,
    createdAt: daysAgo(180),
  },
  {
    id: "rwd_medici_beans",
    merchantId: "mch_medici",
    name: "Bag of Beans",
    description: "12oz bag of house roast to take home.",
    pointsRequired: 250,
    isActive: true,
    createdAt: daysAgo(96),
  },
  {
    id: "rwd_medici_holiday",
    merchantId: "mch_medici",
    name: "Holiday Latte",
    description: "Seasonal drink, retired after last winter.",
    pointsRequired: 120,
    isActive: false,
    createdAt: daysAgo(320),
  },
  {
    id: "rwd_pterrys_fries",
    merchantId: "mch_pterrys",
    name: "Free Fries",
    description: "Regular order of fresh-cut fries.",
    pointsRequired: 40,
    isActive: true,
    createdAt: daysAgo(150),
  },
  {
    id: "rwd_pterrys_burger",
    merchantId: "mch_pterrys",
    name: "Free Burger",
    description: "Classic hamburger with all the fixings.",
    pointsRequired: 75,
    isActive: true,
    createdAt: daysAgo(150),
  },
  {
    id: "rwd_taco_joint_taco",
    merchantId: "mch_taco_joint",
    name: "Free Taco",
    description: "Any single breakfast or lunch taco.",
    pointsRequired: 60,
    isActive: true,
    createdAt: daysAgo(120),
  },
  {
    id: "rwd_taco_joint_meal",
    merchantId: "mch_taco_joint",
    name: "Free Meal",
    description: "Two tacos, rice, beans and a drink.",
    pointsRequired: 150,
    isActive: true,
    createdAt: daysAgo(120),
  },
  {
    id: "rwd_thunderbird_coldbrew",
    merchantId: "mch_thunderbird",
    name: "Free Cold Brew",
    description: "16oz house cold brew.",
    pointsRequired: 120,
    isActive: true,
    createdAt: daysAgo(90),
  },
  {
    id: "rwd_thunderbird_sandwich",
    merchantId: "mch_thunderbird",
    name: "Breakfast Sandwich",
    description: "Egg, cheese and greens on a brioche bun.",
    pointsRequired: 200,
    isActive: true,
    createdAt: daysAgo(90),
  },
  {
    id: "rwd_juan_taco",
    merchantId: "mch_juan",
    name: "Free Breakfast Taco",
    description: "Bacon, egg and cheese on flour.",
    pointsRequired: 80,
    isActive: true,
    createdAt: daysAgo(75),
  },
  {
    id: "rwd_juan_migas",
    merchantId: "mch_juan",
    name: "Migas Plate",
    description: "The full plate, eggs and all.",
    pointsRequired: 200,
    isActive: true,
    createdAt: daysAgo(75),
  },
  {
    id: "rwd_quacks_cookie",
    merchantId: "mch_quacks",
    name: "Free Cookie",
    description: "Any cookie from the case.",
    pointsRequired: 50,
    isActive: true,
    createdAt: daysAgo(60),
  },
  {
    id: "rwd_via313_slice",
    merchantId: "mch_via313",
    name: "Free Slice",
    description: "One Detroit-style slice.",
    pointsRequired: 90,
    isActive: true,
    createdAt: daysAgo(60),
  },
  {
    id: "rwd_juiceland_smoothie",
    merchantId: "mch_juiceland",
    name: "Free Smoothie",
    description: "Any 16oz smoothie on the menu.",
    pointsRequired: 140,
    isActive: true,
    createdAt: daysAgo(45),
  },
  {
    id: "rwd_thundercloud_sub",
    merchantId: "mch_thundercloud",
    name: "Free Half Sub",
    description: "Half sub with chips.",
    pointsRequired: 100,
    isActive: true,
    createdAt: daysAgo(45),
  },
];

/* -------------------------------------------------------------------------- */
/* Customer transactions                                                       */
/* -------------------------------------------------------------------------- */

export const mockTransactions: PointTransaction[] = [
  {
    id: "txn_001",
    walletId: "wal_medici",
    merchantId: "mch_medici",
    locationId: "loc_medici_guadalupe",
    type: "earn",
    pointsDelta: 8,
    amountCents: 875,
    description: "$8.75 purchase",
    createdAt: daysAgo(0, 8, 42),
  },
  {
    id: "txn_002",
    walletId: "wal_pterrys",
    merchantId: "mch_pterrys",
    locationId: "loc_pterrys_guadalupe",
    type: "earn",
    pointsDelta: 12,
    amountCents: 1240,
    description: "$12.40 purchase",
    createdAt: daysAgo(1, 19, 5),
  },
  {
    id: "txn_003",
    walletId: "wal_taco_joint",
    merchantId: "mch_taco_joint",
    locationId: "loc_taco_joint_duval",
    type: "earn",
    pointsDelta: 21,
    amountCents: 2115,
    description: "$21.15 purchase",
    createdAt: daysAgo(2, 12, 30),
  },
  {
    id: "txn_004",
    walletId: "wal_medici",
    merchantId: "mch_medici",
    locationId: "loc_medici_guadalupe",
    type: "earn",
    pointsDelta: 6,
    amountCents: 640,
    description: "$6.40 purchase",
    createdAt: daysAgo(3, 8, 15),
  },
  {
    id: "txn_005",
    walletId: "wal_medici",
    merchantId: "mch_medici",
    locationId: "loc_medici_guadalupe",
    type: "redeem",
    pointsDelta: -100,
    amountCents: null,
    description: "Free Drink",
    createdAt: daysAgo(4, 9, 5),
  },
  {
    id: "txn_006",
    walletId: "wal_thunderbird",
    merchantId: "mch_thunderbird",
    locationId: "loc_thunderbird_manor",
    type: "earn",
    pointsDelta: 14,
    amountCents: 1425,
    description: "$14.25 purchase",
    createdAt: daysAgo(5, 10, 10),
  },
  {
    id: "txn_007",
    walletId: "wal_pterrys",
    merchantId: "mch_pterrys",
    locationId: "loc_pterrys_barton",
    type: "earn",
    pointsDelta: 9,
    amountCents: 980,
    description: "$9.80 purchase",
    createdAt: daysAgo(6, 13, 20),
  },
  {
    id: "txn_008",
    walletId: "wal_taco_joint",
    merchantId: "mch_taco_joint",
    locationId: "loc_taco_joint_duval",
    type: "earn",
    pointsDelta: 11,
    amountCents: 1160,
    description: "$11.60 purchase",
    createdAt: daysAgo(7, 8, 5),
  },
  {
    id: "txn_009",
    walletId: "wal_juan",
    merchantId: "mch_juan",
    locationId: "loc_juan_east",
    type: "earn",
    pointsDelta: 18,
    amountCents: 1830,
    description: "$18.30 purchase",
    createdAt: daysAgo(9, 9, 25),
  },
  {
    id: "txn_010",
    walletId: "wal_medici",
    merchantId: "mch_medici",
    locationId: "loc_medici_west_lynn",
    type: "earn",
    pointsDelta: 7,
    amountCents: 720,
    description: "$7.20 purchase",
    createdAt: daysAgo(11, 7, 55),
  },
  {
    id: "txn_011",
    walletId: "wal_taco_joint",
    merchantId: "mch_taco_joint",
    locationId: "loc_taco_joint_riverside",
    type: "redeem",
    pointsDelta: -60,
    amountCents: null,
    description: "Free Taco",
    createdAt: daysAgo(13, 12, 5),
  },
  {
    id: "txn_012",
    walletId: "wal_thunderbird",
    merchantId: "mch_thunderbird",
    locationId: "loc_thunderbird_manor",
    type: "earn",
    pointsDelta: 16,
    amountCents: 1690,
    description: "$16.90 purchase",
    createdAt: daysAgo(16, 15, 40),
  },
  {
    id: "txn_013",
    walletId: "wal_medici",
    merchantId: "mch_medici",
    locationId: "loc_medici_guadalupe",
    type: "adjustment",
    pointsDelta: 5,
    amountCents: null,
    description: "Goodwill adjustment from staff",
    createdAt: daysAgo(19, 11, 0),
  },
  {
    id: "txn_014",
    walletId: "wal_pterrys",
    merchantId: "mch_pterrys",
    locationId: "loc_pterrys_guadalupe",
    type: "earn",
    pointsDelta: 15,
    amountCents: 1545,
    description: "$15.45 purchase",
    createdAt: daysAgo(22, 18, 30),
  },
];

export const mockRedemptions: Redemption[] = [
  {
    id: "rdm_001",
    rewardId: "rwd_medici_drink",
    walletId: "wal_medici",
    merchantId: "mch_medici",
    userId: MOCK_CURRENT_USER_ID,
    pointsSpent: 100,
    status: "completed",
    redeemedAt: daysAgo(4, 9, 5),
  },
  {
    id: "rdm_002",
    rewardId: "rwd_taco_joint_taco",
    walletId: "wal_taco_joint",
    merchantId: "mch_taco_joint",
    userId: MOCK_CURRENT_USER_ID,
    pointsSpent: 60,
    status: "completed",
    redeemedAt: daysAgo(13, 12, 5),
  },
];

/* -------------------------------------------------------------------------- */
/* Merchant side data (Medici Roasting is the signed-in merchant)              */
/* -------------------------------------------------------------------------- */

export const mockMerchantCustomers: MerchantCustomer[] = [
  {
    id: "mcu_001",
    merchantId: "mch_medici",
    userId: MOCK_CURRENT_USER_ID,
    displayName: "Vishanth Hari",
    pointsBalance: 82,
    visitCount: 14,
    lifetimePoints: 612,
    rewardsRedeemed: 5,
    lastVisitAt: daysAgo(0, 8, 42),
  },
  {
    id: "mcu_002",
    merchantId: "mch_medici",
    userId: "usr_amara",
    displayName: "Amara Osei",
    pointsBalance: 246,
    visitCount: 31,
    lifetimePoints: 1480,
    rewardsRedeemed: 12,
    lastVisitAt: daysAgo(0, 10, 12),
  },
  {
    id: "mcu_003",
    merchantId: "mch_medici",
    userId: "usr_diego",
    displayName: "Diego Ramirez",
    pointsBalance: 58,
    visitCount: 9,
    lifetimePoints: 318,
    rewardsRedeemed: 2,
    lastVisitAt: daysAgo(1, 7, 50),
  },
  {
    id: "mcu_004",
    merchantId: "mch_medici",
    userId: "usr_priya",
    displayName: "Priya Nair",
    pointsBalance: 310,
    visitCount: 42,
    lifetimePoints: 2110,
    rewardsRedeemed: 18,
    lastVisitAt: daysAgo(1, 16, 25),
  },
  {
    id: "mcu_005",
    merchantId: "mch_medici",
    userId: "usr_jonah",
    displayName: "Jonah Feldman",
    pointsBalance: 12,
    visitCount: 2,
    lifetimePoints: 12,
    rewardsRedeemed: 0,
    lastVisitAt: daysAgo(3, 9, 5),
  },
  {
    id: "mcu_006",
    merchantId: "mch_medici",
    userId: "usr_sofia",
    displayName: "Sofia Marquez",
    pointsBalance: 175,
    visitCount: 22,
    lifetimePoints: 940,
    rewardsRedeemed: 7,
    lastVisitAt: daysAgo(4, 11, 45),
  },
  {
    id: "mcu_007",
    merchantId: "mch_medici",
    userId: "usr_tyler",
    displayName: "Tyler Nguyen",
    pointsBalance: 96,
    visitCount: 11,
    lifetimePoints: 496,
    rewardsRedeemed: 3,
    lastVisitAt: daysAgo(5, 8, 30),
  },
  {
    id: "mcu_008",
    merchantId: "mch_medici",
    userId: "usr_grace",
    displayName: "Grace Kim",
    pointsBalance: 34,
    visitCount: 5,
    lifetimePoints: 134,
    rewardsRedeemed: 1,
    lastVisitAt: daysAgo(6, 14, 15),
  },
  {
    id: "mcu_009",
    merchantId: "mch_medici",
    userId: "usr_marcus",
    displayName: "Marcus Webb",
    pointsBalance: 128,
    visitCount: 17,
    lifetimePoints: 728,
    rewardsRedeemed: 6,
    lastVisitAt: daysAgo(8, 9, 55),
  },
  {
    id: "mcu_010",
    merchantId: "mch_medici",
    userId: "usr_leah",
    displayName: "Leah Bennett",
    pointsBalance: 61,
    visitCount: 8,
    lifetimePoints: 261,
    rewardsRedeemed: 2,
    lastVisitAt: daysAgo(12, 13, 5),
  },
];

/** Transactions recorded by the merchant, across all of their customers. */
export const mockMerchantTransactions: Array<{
  transaction: PointTransaction;
  customerName: string;
}> = [
  {
    customerName: "Amara Osei",
    transaction: {
      id: "mtx_001",
      walletId: "wal_amara_medici",
      merchantId: "mch_medici",
      locationId: "loc_medici_guadalupe",
      type: "earn",
      pointsDelta: 14,
      amountCents: 1450,
      description: "$14.50 purchase",
      createdAt: daysAgo(0, 10, 12),
    },
  },
  {
    customerName: "Vishanth Hari",
    transaction: {
      id: "mtx_002",
      walletId: "wal_medici",
      merchantId: "mch_medici",
      locationId: "loc_medici_guadalupe",
      type: "earn",
      pointsDelta: 8,
      amountCents: 875,
      description: "$8.75 purchase",
      createdAt: daysAgo(0, 8, 42),
    },
  },
  {
    customerName: "Priya Nair",
    transaction: {
      id: "mtx_003",
      walletId: "wal_priya_medici",
      merchantId: "mch_medici",
      locationId: "loc_medici_west_lynn",
      type: "redeem",
      pointsDelta: -100,
      amountCents: null,
      description: "Free Drink",
      createdAt: daysAgo(0, 8, 5),
    },
  },
  {
    customerName: "Diego Ramirez",
    transaction: {
      id: "mtx_004",
      walletId: "wal_diego_medici",
      merchantId: "mch_medici",
      locationId: "loc_medici_guadalupe",
      type: "earn",
      pointsDelta: 6,
      amountCents: 610,
      description: "$6.10 purchase",
      createdAt: daysAgo(1, 7, 50),
    },
  },
  {
    customerName: "Sofia Marquez",
    transaction: {
      id: "mtx_005",
      walletId: "wal_sofia_medici",
      merchantId: "mch_medici",
      locationId: "loc_medici_congress",
      type: "earn",
      pointsDelta: 23,
      amountCents: 2340,
      description: "$23.40 purchase",
      createdAt: daysAgo(1, 12, 5),
    },
  },
  {
    customerName: "Tyler Nguyen",
    transaction: {
      id: "mtx_006",
      walletId: "wal_tyler_medici",
      merchantId: "mch_medici",
      locationId: "loc_medici_guadalupe",
      type: "redeem",
      pointsDelta: -75,
      amountCents: null,
      description: "Free Pastry",
      createdAt: daysAgo(2, 9, 30),
    },
  },
];

/** Per-customer transaction history for the merchant customer detail panel. */
export const mockMerchantCustomerTransactions: Record<string, PointTransaction[]> = {
  mcu_001: [
    mockTransactions[0],
    mockTransactions[3],
    mockTransactions[4],
    mockTransactions[9],
  ],
  mcu_002: [
    {
      id: "mtx_amara_1",
      walletId: "wal_amara_medici",
      merchantId: "mch_medici",
      locationId: "loc_medici_guadalupe",
      type: "earn",
      pointsDelta: 14,
      amountCents: 1450,
      description: "$14.50 purchase",
      createdAt: daysAgo(0, 10, 12),
    },
    {
      id: "mtx_amara_2",
      walletId: "wal_amara_medici",
      merchantId: "mch_medici",
      locationId: "loc_medici_guadalupe",
      type: "earn",
      pointsDelta: 9,
      amountCents: 940,
      description: "$9.40 purchase",
      createdAt: daysAgo(2, 8, 30),
    },
    {
      id: "mtx_amara_3",
      walletId: "wal_amara_medici",
      merchantId: "mch_medici",
      locationId: "loc_medici_west_lynn",
      type: "redeem",
      pointsDelta: -75,
      amountCents: null,
      description: "Free Pastry",
      createdAt: daysAgo(5, 9, 0),
    },
  ],
  mcu_004: [
    {
      id: "mtx_priya_1",
      walletId: "wal_priya_medici",
      merchantId: "mch_medici",
      locationId: "loc_medici_west_lynn",
      type: "redeem",
      pointsDelta: -100,
      amountCents: null,
      description: "Free Drink",
      createdAt: daysAgo(0, 8, 5),
    },
    {
      id: "mtx_priya_2",
      walletId: "wal_priya_medici",
      merchantId: "mch_medici",
      locationId: "loc_medici_west_lynn",
      type: "earn",
      pointsDelta: 19,
      amountCents: 1975,
      description: "$19.75 purchase",
      createdAt: daysAgo(3, 7, 45),
    },
  ],
};

export const mockMerchantRedemptions: Record<string, Redemption[]> = {
  mcu_001: mockRedemptions.filter((redemption) => redemption.merchantId === "mch_medici"),
  mcu_002: [
    {
      id: "rdm_amara_1",
      rewardId: "rwd_medici_pastry",
      walletId: "wal_amara_medici",
      merchantId: "mch_medici",
      userId: "usr_amara",
      pointsSpent: 75,
      status: "completed",
      redeemedAt: daysAgo(5, 9, 0),
    },
  ],
  mcu_004: [
    {
      id: "rdm_priya_1",
      rewardId: "rwd_medici_drink",
      walletId: "wal_priya_medici",
      merchantId: "mch_medici",
      userId: "usr_priya",
      pointsSpent: 100,
      status: "completed",
      redeemedAt: daysAgo(0, 8, 5),
    },
  ],
};

export const mockDashboardStats: Record<string, MerchantDashboardStats> = {
  today: {
    customers: 128,
    customersDeltaPercent: 12,
    transactions: 214,
    transactionsDeltaPercent: 8,
    pointsIssued: 1842,
    pointsIssuedDeltaPercent: 15,
    rewardsRedeemed: 17,
    rewardsRedeemedDeltaPercent: -4,
  },
  week: {
    customers: 742,
    customersDeltaPercent: 9,
    transactions: 1386,
    transactionsDeltaPercent: 11,
    pointsIssued: 11940,
    pointsIssuedDeltaPercent: 6,
    rewardsRedeemed: 96,
    rewardsRedeemedDeltaPercent: 3,
  },
  month: {
    customers: 2814,
    customersDeltaPercent: 4,
    transactions: 5921,
    transactionsDeltaPercent: 7,
    pointsIssued: 48310,
    pointsIssuedDeltaPercent: 5,
    rewardsRedeemed: 402,
    rewardsRedeemedDeltaPercent: 10,
  },
};

export const mockPopularRewards: Array<{ rewardId: string; redemptionCount: number }> = [
  { rewardId: "rwd_medici_drink", redemptionCount: 214 },
  { rewardId: "rwd_medici_pastry", redemptionCount: 138 },
  { rewardId: "rwd_medici_beans", redemptionCount: 42 },
];

/**
 * The customer the merchant scanner returns for the "simulate scan" button.
 * Matches the QR token produced by `lib/mock-qr.ts` for the demo member id.
 */
export const MOCK_SCANNED_CUSTOMER_ID = MOCK_CURRENT_USER_ID;
